// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export function getDatabaseInstances(args: GetDatabaseInstancesArgs, opts?: pulumi.InvokeOptions): Promise<GetDatabaseInstancesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("turso:index/getDatabaseInstances:getDatabaseInstances", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDatabaseInstances.
 */
export interface GetDatabaseInstancesArgs {
    id: string;
}

/**
 * A collection of values returned by getDatabaseInstances.
 */
export interface GetDatabaseInstancesResult {
    readonly id: string;
    readonly instances: outputs.GetDatabaseInstancesInstance[];
}
export function getDatabaseInstancesOutput(args: GetDatabaseInstancesOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetDatabaseInstancesResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("turso:index/getDatabaseInstances:getDatabaseInstances", {
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getDatabaseInstances.
 */
export interface GetDatabaseInstancesOutputArgs {
    id: pulumi.Input<string>;
}
