// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "./utilities";

export function getGroupToken(args: GetGroupTokenArgs, opts?: pulumi.InvokeOptions): Promise<GetGroupTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invoke("turso:index/getGroupToken:getGroupToken", {
        "authorization": args.authorization,
        "expiration": args.expiration,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGroupToken.
 */
export interface GetGroupTokenArgs {
    authorization?: string;
    expiration?: string;
    id: string;
}

/**
 * A collection of values returned by getGroupToken.
 */
export interface GetGroupTokenResult {
    readonly authorization: string;
    readonly expiration: string;
    readonly id: string;
    readonly jwt: string;
}
export function getGroupTokenOutput(args: GetGroupTokenOutputArgs, opts?: pulumi.InvokeOptions): pulumi.Output<GetGroupTokenResult> {
    opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts || {});
    return pulumi.runtime.invokeOutput("turso:index/getGroupToken:getGroupToken", {
        "authorization": args.authorization,
        "expiration": args.expiration,
        "id": args.id,
    }, opts, utilities.getPackage());
}

/**
 * A collection of arguments for invoking getGroupToken.
 */
export interface GetGroupTokenOutputArgs {
    authorization?: pulumi.Input<string>;
    expiration?: pulumi.Input<string>;
    id: pulumi.Input<string>;
}
