// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "./types/input";
import * as outputs from "./types/output";
import * as utilities from "./utilities";

export class Group extends pulumi.CustomResource {
    /**
     * Get an existing Group resource's state with the given name, ID, and optional extra
     * properties used to qualify the lookup.
     *
     * @param name The _unique_ name of the resulting resource.
     * @param id The _unique_ provider ID of the resource to lookup.
     * @param state Any extra arguments used during the lookup.
     * @param opts Optional settings to control the behavior of the CustomResource.
     */
    public static get(name: string, id: pulumi.Input<pulumi.ID>, state?: GroupState, opts?: pulumi.CustomResourceOptions): Group {
        return new Group(name, <any>state, { ...opts, id: id });
    }

    /** @internal */
    public static readonly __pulumiType = 'turso:index/group:Group';

    /**
     * Returns true if the given object is an instance of Group.  This is designed to work even
     * when multiple copies of the Pulumi SDK have been loaded into the same process.
     */
    public static isInstance(obj: any): obj is Group {
        if (obj === undefined || obj === null) {
            return false;
        }
        return obj['__pulumiType'] === Group.__pulumiType;
    }

    /**
     * Set to `all` to enable all extensions.
     */
    public readonly extensions!: pulumi.Output<string>;
    public /*out*/ readonly group!: pulumi.Output<outputs.GroupGroup>;
    /**
     * The name of the group.
     */
    public readonly groupId!: pulumi.Output<string>;
    /**
     * All locations for the new group.
     */
    public readonly locations!: pulumi.Output<string[]>;
    /**
     * The name of the new group.
     */
    public readonly name!: pulumi.Output<string>;
    /**
     * The primary location key for the new group.
     */
    public readonly primary!: pulumi.Output<string>;

    /**
     * Create a Group resource with the given unique name, arguments, and options.
     *
     * @param name The _unique_ name of the resource.
     * @param args The arguments to use to populate this resource's properties.
     * @param opts A bag of options that control this resource's behavior.
     */
    constructor(name: string, args: GroupArgs, opts?: pulumi.CustomResourceOptions)
    constructor(name: string, argsOrState?: GroupArgs | GroupState, opts?: pulumi.CustomResourceOptions) {
        let resourceInputs: pulumi.Inputs = {};
        opts = opts || {};
        if (opts.id) {
            const state = argsOrState as GroupState | undefined;
            resourceInputs["extensions"] = state ? state.extensions : undefined;
            resourceInputs["group"] = state ? state.group : undefined;
            resourceInputs["groupId"] = state ? state.groupId : undefined;
            resourceInputs["locations"] = state ? state.locations : undefined;
            resourceInputs["name"] = state ? state.name : undefined;
            resourceInputs["primary"] = state ? state.primary : undefined;
        } else {
            const args = argsOrState as GroupArgs | undefined;
            if ((!args || args.locations === undefined) && !opts.urn) {
                throw new Error("Missing required property 'locations'");
            }
            if ((!args || args.primary === undefined) && !opts.urn) {
                throw new Error("Missing required property 'primary'");
            }
            resourceInputs["extensions"] = args ? args.extensions : undefined;
            resourceInputs["groupId"] = args ? args.groupId : undefined;
            resourceInputs["locations"] = args ? args.locations : undefined;
            resourceInputs["name"] = args ? args.name : undefined;
            resourceInputs["primary"] = args ? args.primary : undefined;
            resourceInputs["group"] = undefined /*out*/;
        }
        opts = pulumi.mergeOptions(utilities.resourceOptsDefaults(), opts);
        super(Group.__pulumiType, name, resourceInputs, opts, false /*dependency*/, utilities.getPackage());
    }
}

/**
 * Input properties used for looking up and filtering Group resources.
 */
export interface GroupState {
    /**
     * Set to `all` to enable all extensions.
     */
    extensions?: pulumi.Input<string>;
    group?: pulumi.Input<inputs.GroupGroup>;
    /**
     * The name of the group.
     */
    groupId?: pulumi.Input<string>;
    /**
     * All locations for the new group.
     */
    locations?: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the new group.
     */
    name?: pulumi.Input<string>;
    /**
     * The primary location key for the new group.
     */
    primary?: pulumi.Input<string>;
}

/**
 * The set of arguments for constructing a Group resource.
 */
export interface GroupArgs {
    /**
     * Set to `all` to enable all extensions.
     */
    extensions?: pulumi.Input<string>;
    /**
     * The name of the group.
     */
    groupId?: pulumi.Input<string>;
    /**
     * All locations for the new group.
     */
    locations: pulumi.Input<pulumi.Input<string>[]>;
    /**
     * The name of the new group.
     */
    name?: pulumi.Input<string>;
    /**
     * The primary location key for the new group.
     */
    primary: pulumi.Input<string>;
}
