// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as inputs from "../types/input";
import * as outputs from "../types/output";

export interface DatabaseDatabase {
    /**
     * The current status for allowing the database to be attached to another.
     */
    allowAttach: boolean;
    /**
     * The current status of the database. If `true`, the database is archived and requires a manual unarchive step.
     */
    archived: boolean;
    /**
     * The current status for blocked reads.
     */
    blockReads: boolean;
    /**
     * The current status for blocked writes.
     */
    blockWrites: boolean;
    /**
     * The database universal unique identifier (UUID).
     */
    dbId: string;
    /**
     * The name of the group the database belongs to.
     */
    group: string;
    /**
     * The DNS hostname used for client libSQL and HTTP connections.
     */
    hostname: string;
    /**
     * If this database controls other child databases then this will be `true`. See [Multi-DB Schemas](https://www.terraform.io/features/multi-db-schemas).
     */
    isSchema: boolean;
    /**
     * The database name, **unique** across your organization.
     */
    name: string;
    /**
     * The primary region location code the group the database belongs to.
     */
    primaryRegion: string;
    /**
     * A list of regions for the group the database belongs to.
     */
    regions: string[];
    /**
     * The name of the parent database that owns the schema for this database. See [Multi-DB Schemas](https://www.terraform.io/features/multi-db-schemas).
     */
    schema: string;
    /**
     * The string representing the object type.
     */
    type: string;
    /**
     * The current libSQL version the database is running.
     */
    version: string;
}

export interface DatabaseSeed {
    /**
     * The name of the existing database when `database` is used as a seed type.
     */
    name: string;
    /**
     * A formatted [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601) recovery point to create a database from. This must be within the last 24 hours, or 30 days on the scaler plan.
     */
    timestamp: string;
    /**
     * The type of seed to be used to create a new database.
     */
    type: string;
    /**
     * The URL returned by [upload dump](https://www.terraform.io/api-reference/databases/upload-dump) can be used with the `dump` seed type.
     */
    url: string;
}

export interface GetDatabaseDatabase {
    /**
     * The current status for allowing the database to be attached to another.
     */
    allowAttach: boolean;
    /**
     * The current status of the database. If `true`, the database is archived and requires a manual unarchive step.
     */
    archived: boolean;
    /**
     * The current status for blocked reads.
     */
    blockReads: boolean;
    /**
     * The current status for blocked writes.
     */
    blockWrites: boolean;
    /**
     * The database universal unique identifier (UUID).
     */
    dbId: string;
    /**
     * The name of the group the database belongs to.
     */
    group: string;
    /**
     * The DNS hostname used for client libSQL and HTTP connections.
     */
    hostname: string;
    /**
     * If this database controls other child databases then this will be `true`. See [Multi-DB Schemas](https://www.terraform.io/features/multi-db-schemas).
     */
    isSchema: boolean;
    /**
     * The database name, **unique** across your organization.
     */
    name: string;
    /**
     * The primary region location code the group the database belongs to.
     */
    primaryRegion: string;
    /**
     * A list of regions for the group the database belongs to.
     */
    regions: string[];
    /**
     * The name of the parent database that owns the schema for this database. See [Multi-DB Schemas](https://www.terraform.io/features/multi-db-schemas).
     */
    schema: string;
    /**
     * The string representing the object type.
     */
    type: string;
    /**
     * The current libSQL version the database is running.
     */
    version: string;
}

export interface GetDatabaseInstancesInstance {
    /**
     * The DNS hostname used for client libSQL and HTTP connections (specific to this instance only).
     */
    hostname: string;
    /**
     * The name of the instance (location code).
     */
    name: string;
    /**
     * The location code for the region this instance is located.
     */
    region: string;
    /**
     * The type of database instance this, will be `primary` or `replica`.
     */
    type: string;
    /**
     * The instance universal unique identifier (UUID).
     */
    uuid: string;
}

export interface GetDatabasesDatabase {
    /**
     * The current status for allowing the database to be attached to another.
     */
    allowAttach: boolean;
    /**
     * The current status of the database. If `true`, the database is archived and requires a manual unarchive step.
     */
    archived: boolean;
    /**
     * The current status for blocked reads.
     */
    blockReads: boolean;
    /**
     * The current status for blocked writes.
     */
    blockWrites: boolean;
    /**
     * The database universal unique identifier (UUID).
     */
    dbId: string;
    /**
     * The name of the group the database belongs to.
     */
    group: string;
    /**
     * The DNS hostname used for client libSQL and HTTP connections.
     */
    hostname: string;
    /**
     * If this database controls other child databases then this will be `true`. See [Multi-DB Schemas](https://www.terraform.io/features/multi-db-schemas).
     */
    isSchema: boolean;
    /**
     * The database name, **unique** across your organization.
     */
    name: string;
    /**
     * The primary region location code the group the database belongs to.
     */
    primaryRegion: string;
    /**
     * A list of regions for the group the database belongs to.
     */
    regions: string[];
    /**
     * The name of the parent database that owns the schema for this database. See [Multi-DB Schemas](https://www.terraform.io/features/multi-db-schemas).
     */
    schema: string;
    /**
     * The string representing the object type.
     */
    type: string;
    /**
     * The current libSQL version the database is running.
     */
    version: string;
}

export interface GetGroupGroup {
    /**
     * Groups on the free tier get archived after some inactivity.
     */
    archived: boolean;
    /**
     * An array of location keys the group is located.
     */
    locations: string[];
    /**
     * The group name, unique across your organization.
     */
    name: string;
    /**
     * The primary location key.
     */
    primary: string;
    /**
     * The group universal unique identifier (UUID).
     */
    uuid: string;
    /**
     * The current libSQL server version the databases in that group are running.
     */
    version: string;
}

export interface GetGroupsGroup {
    /**
     * Groups on the free tier get archived after some inactivity.
     */
    archived: boolean;
    /**
     * An array of location keys the group is located.
     */
    locations: string[];
    /**
     * The group name, unique across your organization.
     */
    name: string;
    /**
     * The primary location key.
     */
    primary: string;
    /**
     * The group universal unique identifier (UUID).
     */
    uuid: string;
    /**
     * The current libSQL server version the databases in that group are running.
     */
    version: string;
}

export interface GroupGroup {
    /**
     * Groups on the free tier get archived after some inactivity.
     */
    archived: boolean;
    /**
     * An array of location keys the group is located.
     */
    locations: string[];
    /**
     * The group name, unique across your organization.
     */
    name: string;
    /**
     * The primary location key.
     */
    primary: string;
    /**
     * The group universal unique identifier (UUID).
     */
    uuid: string;
    /**
     * The current libSQL server version the databases in that group are running.
     */
    version: string;
}

